apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-runner-deployment
  namespace: actions-runner-system
spec:
  replicas: 0
  template:
    spec:
      repository: khalifa7867/GHA-Project-1
      image: summerwind/actions-runner-dind:latest
      serviceAccountName: github-runner-sa
      labels:
        - self-hosted
        - medium
      githubAPICredentialsFrom:
        secretRef:
          name: controller-manager
      nodeSelector:
        workload-type: github-actions
      tolerations:
        - key: github-actions
          operator: Equal
          value: "true"
          effect: NoSchedule
      resources:
        limits:
          cpu: "1500m"
          memory: "1200Mi"
        requests:
          cpu: "500m"
          memory: "1000Mi"
      dockerdWithinRunnerContainer: true
 


        